org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment
minecraft_version=26.1.2
mc_version = 26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.87
neo_version_range=[26.1.2,)
loader_version_range=[4,)

# Mod properties
mod_id=sfmgui
mod_name=Super Factory Manager Visual GUI
mod_license=Mozilla Public License Version 2.0
mod_version=1.0.5
mod_group_id=ca.teamdman.sfmgui
mod_authors=TeamDman
mod_description=Adds a node/wire based visual program editor for Super Factory Manager.\nBuild factory programs by dragging nodes instead of writing SFML by hand.

jei_version = 29.21.0.66


